import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"

import { sarabun } from "../fonts";

import "../globals.css";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
