import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"

import { sarabun } from "../fonts";

import "../globals.css";
import DLayout from "./dashboard/components/DLayout";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
        <DLayout>
          {children}
        </DLayout>
        <Toaster richColors />
      </body>
    </html>
  );
}
