import type { Metadata } from "next";

import "../globals.css";
import { kanit } from "../fonts"; 
import AppHeader from "@/components/app/AppHeader";
import { Toaster } from "@/components/ui/sonner"

// import อันเดียว font อื่นเข้ามาเอง Auto //


export const metadata: Metadata = {
  title: "Advanced Next.js 15.x",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <AppHeader/>
        <Toaster richColors />
        {children}
      </body>
    </html>
  );
}
